### ISSUE TITLE
Set SSL for https in AKS azure

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckan-helm#24]
Hi, I want to set ssl https for my deployed ckan in AKS azure. Is it something related setting the ingress in values.yaml?. Thanks

**Comment by blazhovsky** [comment]
Hi @pribadihcr. On the CKAN side you only need to set the ingress url and maybe the tls secret depending on where you are resolving ssl.

Here is where you can edit the ingress (and ingressRoute if you are using Traefik v2): https://github.com/keitaroinc/ckan-helm/blob/master/values.yaml#L191

If you are using a certificate created in Azure Key Vault you can also use https://akv2k8s.io/tutorials/sync/2-certificate/

I will close this now since it's not an issue but more of an information request. For next time please use our gitter chat here: https://gitter.im/keitaroinc/docker-ckan

I see that you already have questions there that we have discussed.
