### ISSUE TITLE
psql init error

### ISSUE THREAD

**Issue by pribadihcr** [keitaroinc/ckan-helm#26]
Hi I got the following error when deploying in azure kubernates (AKS): kubectl logs psql-init-wgwp5

```
Master DB: postgres Master User: postgres
Checking whether database is up...
Creating user ckan_default
ERROR DB:  role "ckan_default" already exists

Creating user datastorerw
ERROR DB:  role "datastorerw" already exists

Creating user datastorero
ERROR DB:  role "datastorero" already exists

Creating database ckan_default with owner ckan_default
ERROR DB:  database "ckan_default" already exists

Creating database datastore_default with owner datastorerw
ERROR DB:  database "datastore_default" already exists

Traceback (most recent call last):
  File "/srv/psql-init/psql-init.py", line 176, in <module>
    sql = subprocess.check_output(["/usr/bin/ckan",
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ckan'
```

**Comment by mbocevski** [comment]
Was the database empty? Cause the logs say that the roles were already existing in the DB.

**Comment by blazhovsky** [comment]
@pribadihcr it seems that your database already exists. It also seems like you are using a CKAN version that is older than 2.9, that's why you have the `FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ckan'` error. You will need to edit the scripts for this to work, since older CKAN versions use `paster --plugins=ckan...` instead of just ckan.

**Comment by wardtest** [comment]
I was able to reproduce this issue by simply changing the image tag from 2.9.2 to 2.9.2-focal (i.e. using the ubuntu based image instead of the alpine one) using a clean (no existing PVCs) minikube install/setup.  Is this an issue that should be brought up on the docker-ckan repo as there seems to be some difference in the artifacts produced?
